# Selecting a Chisel

`CC-BY 2025 Brooksbank, Kassabov, Wilson`

Start by loading `Dleto.jl`.  If this is your first time you may need to install auxilary packages and possibly set up Julia for notebooks.  That is a one-time setup for most users, see instructions here or consider using the fully online Binder demonstration.

---

> **Technical Note** This experiment uses random Gaussian distributions of floating point numbers.  Changing to other random models, e.g. using `rand(...)` in place of `randn(...)` can result in further features.  This is meant as a general tutorial and invidial contexts will have varried outcomes.

In [ ]:
# Uncomment and run once if Dleto is not installed
using Pkg
# Option 1: To install from remote repository, use:
# Pkg.add(url="https://github.com/thetensor-space/OpenDleto")
# Option 2: If cloned locally, use:
Pkg.activate( "../../" )
Pkg.precompile()

In [5]:
using ITensors
using Dleto

## Chiseling for Radicals

Our first experiment is the simplest demonstration of chiseling uncovering some form of structure.  This 
We create two tensors, one randomized for control, and a identical in size but with 2 rows, columns, and slices set to all zero.  We then randomize the experiment tensor by applying a change in coordinates.
The goal is to using chiseling to detect and recover the hidden zero rows/columns/slices.

We note that this experiment is extremely basic and there are faster algorithms to recover this structure known under the names of **detecting radicals** or **Tucker decompositions**.  `Delto.jl` makes use of those faster methods for large scale experiments, but this experiment simply uses generic Delto methods to explore what is possible.


> **Note** Julia being mathematically oriented accepts $\LaTeX$ styled commands with tab-completion.  For example to insert the Unicode character for $\Gamma$ use `\Gamma` in the code area followed by `tab` (or cut-and-paste a character you see somewhere else).  Or replace with an simpler string of characters of your liking.  One suggestion, `Dleto.jl` calculations make substantial use of tensors, matrices, and lists of matrices.  A convention that clearly indicates those roles will be an investment worth your time.  
>
> We will be using:
> * capitol Greek letters `Γ` (`\Gamma`), `Δ` (`\Delta`), `Σ` (`\Sigma`), `Ξ` (`\Xi`), `Υ` (`\Upsilon`), etc. for tensors
> * capital English letters `X`, `Y`, `Z` etc. for matrices
> * lower case Geek letters for real numbers
> * lower case English letters for integers
> * Plural for lists of data, for instance `Γs` and `Xs`.

In [2]:
ds = (5,5,5); rs=(3,3,3)
Γ = randn(Float64, ds);  # a control tensor

# the experiment tensor is initially 0 but we fill in a subregion.
Δ = zeros(Float64, ds);  
Δ[1:rs[1], 1:rs[2], 1:rs[3]] .= randn(rs...)

side_by_side(Γ, Δ; left_title="Control Γ", right_title="Experiment Δ")

Control Γ 
 5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -2.01905 0.248658 1.756 -0.999567 -0.220745
 -0.776975 -0.881898 0.649661 -0.389291 -0.272241
 1.50978 -1.45296 -1.79217 0.687403 -0.018403
 -0.826063 -0.688472 0.74849 0.176828 -1.14246
 1.55541 -0.9095 0.155649 -0.296406 0.878553

[:, :, 2] =
 0.701413 -0.81331 -0.753394 1.58322 0.108554
 -0.739426 -0.442479 -0.218672 -1.19729 -0.493061
 -1.14784 -1.1985 -1.78374 0.457021 0.263117
 0.446784 -1.15804 1.09451 0.157746 1.00671
 -0.469585 -1.2102 1.61772 -0.73494 0.0171464

[:, :, 3] =
 -1.46348 -0.0126198 0.178037 0.207107 1.65617
 0.260116 -1.06815 2.06072 0.20919 -0.604306
 0.0886656 1.20457 0.565196 -1.17969 -0.538437
 0.923779 -0.706836 -0.164558 1.41897 0.728937
 -0.26146 0.577035 -0.221095 -1.17304 0.374026

[:, :, 4] =
 0.0822417 -0.0096802 0.394936 0.552511 -1.12108
 0.929854 -0.0559192 -1.73459 -0.180517 0.768487
 1.12019 -1.12257 -0.252229 0.609787 2.08574
 -0.24691 0.946742 1.15258 -0.839734 -1.48468
 -0.480763 0.656542 -0.168628 1.59525 0.367523

[:, :, 5] =
 0.362333 2.15288 -2.208 -1.56417 -0.379008
 -0.853747 -0.711534 -1.40057 -0.355097 0.23693
 0.754116 0.317418 -1.43942 -2.393 0.350979
 0.793066 -0.459213 0.103519 2.79534 -0.731317
 -0.504294 -0.570229 0.0723074 0.267617 -0.519398 
 
 
 Experiment Δ 
 5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -0.592146 -1.72395 -0.661934 0.0 0.0
 0.316628 2.55656 0.132478 0.0 0.0
 0.26885 -2.48441 0.457963 0.0 0.0
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0

[:, :, 2] =
 -1.18753 0.37529 1.49551 0.0 0.0
 -0.150643 -0.479692 0.331151 0.0 0.0
 -0.52803 -0.328576 -0.676734 0.0 0.0
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0

[:, :, 3] =
 0.824364 0.383832 -0.438603 0.0 0.0
 1.58158 -0.0137606 -0.544 0.0 0.0
 -1.42486 0.0339164 -1.88293 0.0 0.0
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0

[:, :, 4] =
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0

[:, :, 5] =
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0

The control tensor very likely has few to no all zero axes whereas the experiment evidently does.  The role of chiseling is to recover such anamolies without knowing ahead of time.  So we now randomize the experiment so as to obscure this data.  Note that the randomization applies random bases change so the original coordinates.  

It should now be much less obvious that the control and experminet are any different.

In [3]:
Ξ, Xs = randomize_tensor(Δ);  # In theory Ξ = Δ*Xs

# Equality check is often too strict, approximate check is better
isapprox(Δ*Xs, Ξ)

true

If you attempt to display `Ξ` you may discover `randomize` has switched the internal representation of tensors the `ITensor` format.  In fact this why we are able to apply a **list** (Julia `Vector` types) of matrices to `Δ` without specifying what side to multiply on.  The order is immaterial, for example `Xs*Δ` is allowable as well.  This is in contrast to matrix multiplication where sides indicate the axis of application.  `ITensors` uses internal markers to permit the correct application across multiple axes.

To see the contents in its original array format you can use `asarray(Δ)`.

In [6]:
side_by_side(Γ, Array(Ξ, inds(Ξ)); left_title="Control Γ", right_title="Experiment Ξ")

Control Γ 
 5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -2.01905 0.248658 1.756 -0.999567 -0.220745
 -0.776975 -0.881898 0.649661 -0.389291 -0.272241
 1.50978 -1.45296 -1.79217 0.687403 -0.018403
 -0.826063 -0.688472 0.74849 0.176828 -1.14246
 1.55541 -0.9095 0.155649 -0.296406 0.878553

[:, :, 2] =
 0.701413 -0.81331 -0.753394 1.58322 0.108554
 -0.739426 -0.442479 -0.218672 -1.19729 -0.493061
 -1.14784 -1.1985 -1.78374 0.457021 0.263117
 0.446784 -1.15804 1.09451 0.157746 1.00671
 -0.469585 -1.2102 1.61772 -0.73494 0.0171464

[:, :, 3] =
 -1.46348 -0.0126198 0.178037 0.207107 1.65617
 0.260116 -1.06815 2.06072 0.20919 -0.604306
 0.0886656 1.20457 0.565196 -1.17969 -0.538437
 0.923779 -0.706836 -0.164558 1.41897 0.728937
 -0.26146 0.577035 -0.221095 -1.17304 0.374026

[:, :, 4] =
 0.0822417 -0.0096802 0.394936 0.552511 -1.12108
 0.929854 -0.0559192 -1.73459 -0.180517 0.768487
 1.12019 -1.12257 -0.252229 0.609787 2.08574
 -0.24691 0.946742 1.15258 -0.839734 -1.48468
 -0.480763 0.656542 -0.168628 1.59525 0.367523

[:, :, 5] =
 0.362333 2.15288 -2.208 -1.56417 -0.379008
 -0.853747 -0.711534 -1.40057 -0.355097 0.23693
 0.754116 0.317418 -1.43942 -2.393 0.350979
 0.793066 -0.459213 0.103519 2.79534 -0.731317
 -0.504294 -0.570229 0.0723074 0.267617 -0.519398 
 
 
 Experiment Ξ 
 5×5×5 Array{Float64, 3}:
[:, :, 1] =
 -0.920004 -4.74596 1.93046 1.24384 -9.34161
 0.556048 -3.09508 -0.30717 0.890458 -8.5044
 0.726215 0.99714 -1.12382 -0.226597 0.859672
 1.00416 -1.75002 -1.15954 0.57573 -6.37173
 -0.282832 0.891531 0.259867 -0.267434 2.71818

[:, :, 2] =
 -14.2641 11.3977 3.4234 2.79786 22.4616
 10.2294 5.69601 -5.13503 -5.49576 15.1624
 12.7247 -2.92128 -4.63838 -4.22954 -4.14396
 7.48576 -1.58507 -0.112245 -3.80319 4.22833
 -4.01086 -1.07456 1.5328 1.9878 -3.95083

[:, :, 3] =
 -9.52282 4.00713 5.88532 1.36572 13.8699
 5.24731 2.80247 -5.22008 -1.52373 1.22332
 8.01969 -0.62772 -6.038 -1.57404 -6.81457
 -0.33101 -0.0482116 0.247469 0.091408 0.0754463
 -1.70057 -0.650478 1.59318 0.452618 0.0672303

[:, :, 4] =
 -4.91578 0.988526 0.637675 2.24206 -1.56051
 4.36156 -0.645187 -0.691729 -2.00827 1.71191
 4.5781 -0.691133 -0.627055 -2.15119 1.99759
 6.20067 -2.66299 -1.29275 -2.10227 -3.06005
 -1.98022 0.477562 0.341167 0.834886 -0.209698

[:, :, 5] =
 0.191238 -1.92346 5.38036 -2.05778 7.9546
 -3.15008 1.31503 -3.48137 3.08799 -8.51721
 -1.01462 1.49176 -4.92692 2.47144 -9.00558
 -11.0942 3.60821 1.7543 4.43159 0.983679
 2.00037 -0.786325 0.944864 -1.36384 2.49165

Now let us use the default chiselling methods to begin exploring our tensors.

You see the default setting used only 10 of the available 75 values.  The value $75=3\cdot 5^2$ coincides with being a 3-valent tensor with dimensions `(5,5,5)` so it will take three $5\times 5$-operators to manipulate for a total of 75 parameters.  However there are also $125=5^3$ constraint equations so we should expect few solutions.  Thus as a practical improvement, `Dleto.jl` estimates only 10 solutions will be necessary and accelorate the calculations knowing this heuristic value.

To explain the process in full, let us override this heuristic cut-off and take all the available values.  Note, if we give `chisel` a number greater than the available values or one that is negative, then all values are computed. 

In [11]:
# Γ = ITensor(Γ, inds(Ξ))
d1 = der(Γ)
d2 = der(Ξ)
Γ_strat = stratify(Γ,d1[1]);
Ξ_strat = stratify(Ξ,d2[1]);

engaged: Bool[1, 1, 1]
engaged: Bool[1, 1, 1]


Spalls have two types of data, a list of values `xxx_t.values` and a list of vectors `xxx_t.vectors`.  We can example the values by comparing the control to the experiment.  Often plots can communicate the differences.  

## Features
 * In the control, there are 2 values that are very close to zero, followed by a small jump and then gradually growing values.
 * In the experiment with `ds=(5,5,5)` and `rs=(2,2,2)` there are more than 30 nearly 0 values.
 * Both the control and the experiment accelorate near the end.

To experiment further, adjust the dimensions in Cell 2 from `(5,5,5)` to `(3,5,10)`, or increase the random contribution of to `exp_t` from `rand(3,3,3)` to `rand(5,3,3)`.  Rerun each cell in this section and watch for changes.  

In [12]:
# using Pkg; Pkg.add("Plots"). ## uncommnet if Plots not installed, only needed once
using Plots 

p1 = plot(Γ_strat,  xlabel="Index", ylabel="Value", title="Control Spall Values", color=:blue)
p2 = plot(Ξ_strat,  xlabel="Index", ylabel="Value", title="Experiment Spall Values", color=:red)
plot(p1, p2, layout=(1,2), size=(1000, 400))

UndefVarError: UndefVarError: `plot` not defined in `Main`
Hint: It looks like two or more modules export different bindings with this name, resulting in ambiguity. Try explicitly importing it from a particular module, or qualifying the name with the module it should come from.
Hint: a global variable of this name also exists in GR.jlgr.
    - Also exported by GR.
Hint: a global variable of this name also exists in Dleto.
Hint: a global variable of this name also exists in PlotlyJS.
Hint: a global variable of this name also exists in RecipesBase.
    - Also exported by Plots.

The behavior demonstrated is a response to the number of 0's we included as rows, columns, and slices in the experiment.  It may become more noticeable to plot the derviatives, using `diff(xxx_t.values)`.  

Unfortunately, the steep changes in behavior near the final values can overwhellem the comparisons we are after near the small values, which is what we care to track.  Those carry little useable information as we can see they occur at the same range.  It is for this reason that we typically do not include the larger values.  By replotting the data with smaller range we can better see the differences between control and experiment.

**We are interested in the index location of the first spike in the differences.**

In [ ]:
p1 = plot(diff(ctr_spall.values[1:50]),  xlabel="Index", ylabel="Value", title="Control Spall Values", color=:blue)
p2 = plot(diff(exp_spall.values[1:50]),  xlabel="Index", ylabel="Value", title="Experiment Spall Values", color=:red)
plot(p1, p2, layout=(1,2), size=(1000, 400))

You may notice the number of 0's in the experimental plot increase with the number of all zero rows, columns, and slices. You may even be able to estimate a formula on the order of the following.
```math
2 + d_1\cdot r_1 + d_2 \cdot r_2 + d_3\cdot r_3
```
> While not important to chisel selection, the orgin of this formula can be seen as the number of matrices mapping $\mathbb{R}^{d_i}\to \mathbb{R}^{r_i}$ for each axis $i\in \{1,2,3\}$ plus the initial 2 dimensions that are present for all tensors of valence 2.  Note that these numbers are also specific to the universal chisel which we get by default when using `chisel(xxx_t)`.

## Recovering blocks from the chiseling spall


In [ ]:
sculpted_ctr = sculpt(ctr_t, ctr_spall, collect(3:3));
sculpted_exp = sculpt(exp_t, exp_spall, collect(3:3));
sidebyside(round.(100*sculpted_ctr.tensor), round.(100*sculpted_exp.tensor); 
left_title="Control Sculpted Vec", right_title="Experiment Sculpted Vec")